Desktop_Portfolio
AhmadiGu/Desktop_Portfolio pull request #11
Opened 2022-10-20 12:38 UTC by AhmadiGu

### Form local-storage

- add the local storage to store the form data.

2022-10-20 14:01 UTC, Qoosim requested changes
#  *Status: Required Changes* :recycle: 

Hi @team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

-   No linter errors. :heavy_check_mark: 
-   Good README file. :heavy_check_mark: 
-   Correct GitHub Flow. :heavy_check_mark: 

![](https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966)


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

### Hint

You can use this as a guide

```
const formData = {
    name: nameInput.value,
    email: emailInput.value,
    body: bodyInput.value,
};


localStorage.setItem('contactFormInput', JSON.stringify(formData));

let savedFormData = localStorage.getItem('contactFormInput');
savedFormData = JSON.parse(savedFormData);

window.onload = () => {
  let savedFormData = localStorage.getItem('contactFormInput');
  savedFormData = JSON.parse(savedFormData);
  // Check if the form data object is found on localStorage
  if (savedFormData) {
  // populate inputs values if data was found
  // ex: nameInput.value = savedFormData.name
  }
};

```

Best of luck :crossed_fingers:

2022-10-20 14:01 UTC, Qoosim commented on form.js
> +form.message.value = userData.message;
- [REQUIRED] It is required to preserve the users data at the page load. Below features are what your form is expected to display.

-  After filling the form, and not submitting it, the entered values should be saved in the browser.
-  When visiting the page the form inputs should be contained, be auto-populated with, the values entered in the previous visit to the page.
-  If at the previous visit to the page, in the same browser, no input was entered in the form then the form inputs should remain empty.  
Kindly look into this and work your form to display these features.

At this moment, after filling the form with the appropriate data, if I reload the page without clicking on the submit button, I should still have my data preserved for me, but your form behaves contrary to that feature. Kindly make your form to display this feature.

2022-10-21 07:24 UTC, Abenezer-Tilahun approved these changes
Hi @AhmadiGu   ,
 
Your project is complete  👍 💯   There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 👏🏻

✔️ No linter errors.
✔️ You used correct Github Flow.
✔️ Professional README  
✔️ Good Commit Messages


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-21 07:25 UTC, Abenezer-Tilahun commented on form.js
> +form.message.value = userData.message;
Fixed.

2023-05-19 05:09 UTC, merged